### ISSUE TITLE
Cannot install extension

### ISSUE THREAD

**Issue by ernestoalejo** [auth0-extensions/auth0-account-link-extension#84]
When I try to install the extension it says:
> Error trying to install Auth0 Account Link. Please try again later.

I investigated a little bit more and there is a call to this URL, after the `auth0-account-link` application is created:
  https://sandbox12-eu.it.auth0.com/api/run/lavoz/[LARGE_CODE_HERE]/.extensions/on-install

And it returns this error:
```{
  "code": 400,
  "message": "Compilation failed: Cannot assign to read only property 'exports' of object '#<Object>'",
  "error": "Cannot assign to read only property 'exports' of object '#<Object>'",
  "stack": "TypeError: Cannot assign to read only property 'exports' of object '#<Object>'\n    at Module.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:6129)\n    at Module.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:6959)\n    at t (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:124)\n    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:5534)\n    at t (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:124)\n    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:3775)\n    at t (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:124)\n    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:3447)\n    at t (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:124)\n    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:2076)\n    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:2999)\n    at t (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:124)\n    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:1492)\n    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:1828)\n    at t (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:124)\n    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:963)"
}
```

Formatted for easier reading:
```
TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:6129)
    at Module.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:6959)
    at t (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:124)
    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:5534)
    at t (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:124)
    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:3775)
    at t (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:124)
    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:3447)
    at t (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:124)
    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:2076)
    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:2999)
    at t (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:124)
    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:1492)
    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:1828)
    at t (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:124)
    at Object.<anonymous> (/data/io/node12/714b1239-f9fc-46f1-89e3-9b2304c47b92/webtask.js:2:963)
```

**Comment by saltukalakus** [comment]
👋  the issue should be related to [this change](https://github.com/auth0-extensions/auth0-account-link-extension/commit/240d59c2a19d7e4ba384531ba90d12ffdd8de9c3). Could you try reverting the `yarn.lock` file and retry installing the packages.

**Comment by ernestoalejo** [comment]
Well, I'm using the website so there is no code under my control there:

![image](https://user-images.githubusercontent.com/961966/92486313-38752a80-f1ec-11ea-867d-1544d4b981fe.png)

**Comment by ernestoalejo** [comment]
Still relevant, can't use this extension with the official installation

**Comment by ademartini** [comment]
Hey @ernestoalejo we have recently released a new version of this extension.  Is this still reproducable for you?

**Comment by ernestoalejo** [comment]
Let me create a test tenant and I'll tell you shortly if it works.

**Comment by madsharm** [comment]
Closing the issue, I verified that the latest version of extension 2.6.4 is working fine. Please feel free to reopen if you see this issue again.
